"use client";

import { useState } from "react";
import { BRIDGES, SEVERITY_CONFIG } from "@/lib/data";

function generateTxtContent(bridge: typeof BRIDGES[0]) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-PK", {
    year: "numeric", month: "long", day: "numeric"
  });
  const timeStr = now.toLocaleTimeString("en-PK");

  return [
    "╔══════════════════════════════════════════════════╗",
    "║         BRIDGEGUARD AI — HEALTH REPORT           ║",
    "║         AI-Powered Bridge Monitoring System      ║",
    "╚══════════════════════════════════════════════════╝",
    "",
    `Report Date:     ${dateStr}`,
    `Report Time:     ${timeStr}`,
    `Bridge Name:     ${bridge.name}`,
    `Location:        ${bridge.location}`,
    `Sensor ID:       ${bridge.sensor_id}`,
    "",
    "══════════════════════════════════════════════════",
    "RISK ASSESSMENT SUMMARY",
    "══════════════════════════════════════════════════",
    `Risk Score:      ${bridge.risk_score} / 100`,
    `Severity Band:   ${bridge.severity}`,
    `Review Status:   ${bridge.review_status}`,
    `Current RMS:     ${bridge.current_rms} m/s²`,
    "",
    "══════════════════════════════════════════════════",
    "AI RISK EXPLANATION (Agent 3 Output)",
    "══════════════════════════════════════════════════",
    bridge.explanation,
    "",
    "══════════════════════════════════════════════════",
    "MAINTENANCE RECOMMENDATION",
    "══════════════════════════════════════════════════",
    bridge.severity === "CRITICAL"
      ? "IMMEDIATE ACTION: Engineering inspection within 48 hours.\n    Do not delay. Reduce load limits until cleared by engineer."
      : bridge.severity === "WARNING"
      ? "ACTION REQUIRED: Engineering inspection within 14 days.\n    Monitor continuously. Document any new anomalies."
      : bridge.severity === "WATCH"
      ? "MONITOR: Continue standard monitoring.\n    Review readings weekly. No immediate action required."
      : "NO ACTION: All systems within normal range.\n    Next scheduled review in 30 days.",
    "",
    "══════════════════════════════════════════════════",
    "RECENT SENSOR READINGS (Last 10)",
    "══════════════════════════════════════════════════",
    "Time       | RMS (m/s²) | Status",
    "-----------|------------|--------",
    ...Array.from({ length: 10 }, (_, i) => {
      const t = new Date(Date.now() - (10 - i) * 30000);
      const timeLabel = `${String(t.getHours()).padStart(2, "0")}:${String(t.getMinutes()).padStart(2, "0")}:${String(t.getSeconds()).padStart(2, "0")}`;
      const rms = bridge.severity === "CRITICAL"
        ? (2.2 + Math.random() * 0.9).toFixed(3)
        : bridge.severity === "WARNING"
        ? (0.6 + Math.random() * 0.4).toFixed(3)
        : (0.22 + Math.random() * 0.2).toFixed(3);
      const status = parseFloat(rms) > 0.5 ? "HIGH   " : "NORMAL ";
      return `${timeLabel}  | ${rms}      | ${status}`;
    }),
    "",
    "══════════════════════════════════════════════════",
    "ACTIVE ALERTS",
    "══════════════════════════════════════════════════",
    bridge.alerts.length === 0
      ? "No active alerts."
      : bridge.alerts.map(a =>
          `[${a.severity}] ${a.time}\n  ${a.message}`
        ).join("\n\n"),
    "",
    "══════════════════════════════════════════════════",
    "SYSTEM INFORMATION",
    "══════════════════════════════════════════════════",
    "Generated by:    BridgeGuard AI v1.0",
    "Agent pipeline:  5 agents (1,480+ tests, 0 failures)",
    "Data source:     IoT accelerometer via LoRaWAN",
    "Province:        Sindh, Pakistan",
    `Timestamp:       ${now.toISOString()}`,
    "",
    "This report was generated automatically by the",
    "BridgeGuard AI system. All risk scores are",
    "computed deterministically. AI explanations",
    "are generated by Agent 3 (Risk Reasoning Agent).",
    "Critical recommendations require human engineer",
    "sign-off before any action is taken.",
    "",
    "╔══════════════════════════════════════════════════╗",
    "║  BridgeGuard AI — Protecting Pakistan's Bridges  ║",
    "╚══════════════════════════════════════════════════╝",
  ].join("\n");
}

export default function ReportsPage() {
  const [selectedId, setSelectedId] = useState(BRIDGES[0].id);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const bridge = BRIDGES.find((b) => b.id === selectedId)!;
  const cfg = SEVERITY_CONFIG[bridge.severity];

  function downloadTxt() {
    setLoading(true);
    setDone(false);
    setTimeout(() => {
      const content = generateTxtContent(bridge);
      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `BridgeGuard-Report-${bridge.id}-${Date.now()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setLoading(false);
      setDone(true);
    }, 1500);
  }

  function downloadPdf() {
    setLoading(true);
    setTimeout(() => {
      const content = generateTxtContent(bridge);
      const escapedContent = content
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
      const dateStr = new Date().toLocaleDateString("en-PK", {
        year: "numeric", month: "long", day: "numeric"
      });
      const recommendation =
        bridge.severity === "CRITICAL"
          ? "IMMEDIATE: Engineering inspection within 48 hours."
          : bridge.severity === "WARNING"
          ? "ACTION: Engineering inspection within 14 days."
          : bridge.severity === "WATCH"
          ? "MONITOR: Continue monitoring. Review in 7 days."
          : "NO ACTION: All systems normal. Review in 30 days.";

      const printWindow = window.open("", "_blank");
      if (!printWindow) return;
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>BridgeGuard Report — ${bridge.name}</title>
          <style>
            body {
              font-family: 'Courier New', monospace;
              font-size: 12px;
              line-height: 1.6;
              padding: 30px;
              color: #000;
            }
            .header {
              text-align: center;
              border: 2px solid #0F6E56;
              padding: 12px;
              margin-bottom: 20px;
              border-radius: 8px;
            }
            .score {
              font-size: 36px;
              font-weight: bold;
              color: ${cfg.bar};
              text-align: center;
              margin: 12px 0;
            }
            .section {
              margin: 16px 0;
              border-top: 1px solid #ccc;
              padding-top: 10px;
            }
            .badge {
              display: inline-block;
              padding: 4px 12px;
              border-radius: 20px;
              font-weight: bold;
              font-size: 13px;
              background: ${cfg.bgHex};
              color: ${cfg.textHex};
            }
            pre {
              white-space: pre-wrap;
              font-size: 11px;
            }
            @media print {
              body { padding: 20px; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 style="font-size:16px; margin-bottom:8px;">BridgeGuard AI — Bridge Health Report</h1>
            <div>${bridge.name}</div>
            <div>${bridge.location}</div>
            <div>${dateStr}</div>
          </div>
          <div class="score">${bridge.risk_score}/100</div>
          <div style="text-align:center; margin-bottom:16px;">
            <span class="badge">${cfg.label}</span>
          </div>
          <div class="section">
            <strong>AI Risk Assessment (Agent 3 Output):</strong><br/><br/>
            ${bridge.explanation}
          </div>
          <div class="section">
            <strong>Recommendation:</strong><br/><br/>
            ${recommendation}
          </div>
          <div class="section">
            <pre>${escapedContent}</pre>
          </div>
        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
      setLoading(false);
      setDone(true);
    }, 1000);
  }

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">
          Bridge Health Reports
        </h1>
        <p className="text-sm text-gray-500 mt-1">
          Generate official reports for government submission
          or engineering review. Export as TXT or PDF.
        </p>
      </div>

      <div className="bg-white border border-gray-100 rounded-xl p-6 mb-6 shadow-sm">
        <h2 className="text-sm font-semibold text-gray-700 mb-4">
          Generate a new report
        </h2>

        <div className="mb-4">
          <label className="text-xs text-gray-500 mb-2 block font-medium">
            Select bridge
          </label>
          <select
            value={selectedId}
            onChange={(e) => {
              setSelectedId(e.target.value);
              setDone(false);
            }}
            className="w-full p-3 border border-gray-200 rounded-lg text-sm text-gray-700 bg-white focus:outline-none focus:border-gray-400">
            {BRIDGES.map((b) => (
              <option key={b.id} value={b.id}>
                {b.name} — {SEVERITY_CONFIG[b.severity].label}
              </option>
            ))}
          </select>
        </div>

        <div className="p-3 rounded-lg mb-4 text-xs"
          style={{ background: cfg.bgHex, color: cfg.textHex }}>
          <strong>Current status:</strong> Risk score{" "}
          {bridge.risk_score}/100 · {cfg.label} ·{" "}
          {bridge.alerts.length} active alert{bridge.alerts.length !== 1 ? "s" : ""}
        </div>

        <div className="flex gap-3">
          <button
            onClick={downloadTxt}
            disabled={loading}
            className="flex-1 py-3 rounded-lg text-sm font-semibold border-2 transition-opacity disabled:opacity-60"
            style={{
              borderColor: "#0F6E56",
              color: "#0F6E56",
              background: "white"
            }}>
            {loading ? "Generating..." : "📄 Download TXT"}
          </button>
          <button
            onClick={downloadPdf}
            disabled={loading}
            className="flex-1 py-3 rounded-lg text-sm font-semibold text-white transition-opacity disabled:opacity-60"
            style={{ backgroundColor: "#0F6E56" }}>
            {loading ? "Generating..." : "📑 Download PDF"}
          </button>
        </div>

        {loading && (
          <p className="text-xs text-gray-400 mt-3 text-center">
            Assembling report from all 5 agent outputs...
          </p>
        )}

        {done && (
          <div className="mt-4 p-4 rounded-lg"
            style={{ background: "#eaf3de",
                     border: "0.5px solid #3B6D11" }}>
            <p className="text-sm font-semibold mb-1"
              style={{ color: "#3B6D11" }}>
              ✓ Report generated successfully
            </p>
            <p className="text-xs text-gray-500">
              For PDF: allow pop-ups and use
              &quot;Save as PDF&quot; in the print dialog.
            </p>
          </div>
        )}
      </div>

      <div className="bg-white border border-gray-100 rounded-xl p-6 shadow-sm">
        <h2 className="text-sm font-semibold text-gray-700 mb-4">
          What the report includes
        </h2>
        <div className="grid grid-cols-2 gap-3">
          {[
            "Bridge name, location, sensor ID",
            "Risk score (0-100) and severity",
            "AI explanation in plain language",
            "Last 10 sensor readings with RMS",
            "Active alerts with timestamps",
            "Maintenance recommendation",
            "5-agent pipeline attribution",
            "Report timestamp and metadata",
          ].map((item) => (
            <div key={item}
              className="flex items-center gap-2 text-sm text-gray-600">
              <span style={{ color: "#0F6E56" }}>✓</span>
              {item}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
