"use client";

import { useState } from "react";
import { BRIDGES, SEVERITY_CONFIG } from "@/lib/data";

function generateTxtContent(bridge: typeof BRIDGES[0]) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-PK", {
    year: "numeric", month: "long", day: "numeric"
  });
  const timeStr = now.toLocaleTimeString("en-PK");

  return [
    "╔══════════════════════════════════════════════════╗",
    "║         BRIDGEGUARD AI — HEALTH REPORT           ║",
    "║         AI-Powered Bridge Monitoring System      ║",
    "╚══════════════════════════════════════════════════╝",
    "",
    `Report Date:     ${dateStr}`,
    `Report Time:     ${timeStr}`,
    `Bridge Name:     ${bridge.name}`,
    `Location:        ${bridge.location}`,
    `Sensor ID:       ${bridge.sensor_id}`,
    "",
    "══════════════════════════════════════════════════",
    "RISK ASSESSMENT SUMMARY",
    "══════════════════════════════════════════════════",
    `Risk Score:      ${bridge.risk_score} / 100`,
    `Severity Band:   ${bridge.severity}`,
    `Review Status:   ${bridge.review_status}`,
    `Current RMS:     ${bridge.current_rms} m/s²`,
    "",
    "══════════════════════════════════════════════════",
    "AI RISK EXPLANATION (Agent 3 Output)",
    "══════════════════════════════════════════════════",
    bridge.explanation,
    "",
    "══════════════════════════════════════════════════",
    "MAINTENANCE RECOMMENDATION",
    "══════════════════════════════════════════════════",
    bridge.severity === "CRITICAL"
      ? "IMMEDIATE ACTION: Engineering inspection within 48 hours.\n    Do not delay. Reduce load limits until cleared by engineer."
      : bridge.severity === "WARNING"
      ? "ACTION REQUIRED: Engineering inspection within 14 days.\n    Monitor continuously. Document any new anomalies."
      : bridge.severity === "WATCH"
      ? "MONITOR: Continue standard monitoring.\n    Review readings weekly. No immediate action required."
      : "NO ACTION: All systems within normal range.\n    Next scheduled review in 30 days.",
    "",
    "══════════════════════════════════════════════════",
    "RECENT SENSOR READINGS (Last 10)",
    "══════════════════════════════════════════════════",
    "Time       | RMS (m/s²) | Status",
    "-----------|------------|--------",
    ...Array.from({ length: 10 }, (_, i) => {
      const t = new Date(Date.now() - (10 - i) * 30000);
      const timeLabel = `${String(t.getHours()).padStart(2, "0")}:${String(t.getMinutes()).padStart(2, "0")}:${String(t.getSeconds()).padStart(2, "0")}`;
      const rms = bridge.severity === "CRITICAL"
        ? (2.2 + Math.random() * 0.9).toFixed(3)
        : bridge.severity === "WARNING"
        ? (0.6 + Math.random() * 0.4).toFixed(3)
        : (0.22 + Math.random() * 0.2).toFixed(3);
      const status = parseFloat(rms) > 0.5 ? "HIGH   " : "NORMAL ";
      return `${timeLabel}  | ${rms}      | ${status}`;
    }),
    "",
    "══════════════════════════════════════════════════",
    "ACTIVE ALERTS",
    "══════════════════════════════════════════════════",
    bridge.alerts.length === 0
      ? "No active alerts."
      : bridge.alerts.map(a =>
          `[${a.severity}] ${a.time}\n  ${a.message}`
        ).join("\n\n"),
    "",
    "══════════════════════════════════════════════════",
    "SYSTEM INFORMATION",
    "══════════════════════════════════════════════════",
    "Generated by:    BridgeGuard AI v1.0",
    "Agent pipeline:  5 agents (1,480+ tests, 0 failures)",
    "Data source:     IoT accelerometer via LoRaWAN",
    "Province:        Sindh, Pakistan",
    `Timestamp:       ${now.toISOString()}`,
    "",
    "This report was generated automatically by the",
    "BridgeGuard AI system. All risk scores are",
    "computed deterministically. AI explanations",
    "are generated by Agent 3 (Risk Reasoning Agent).",
    "Critical recommendations require human engineer",
    "sign-off before any action is taken.",
    "",
    "╔══════════════════════════════════════════════════╗",
    "║  BridgeGuard AI — Protecting Pakistan's Bridges  ║",
    "╚══════════════════════════════════════════════════╝",
  ].join("\n");
}

export default function ReportsPage() {
  const [selectedId, setSelectedId] = useState(BRIDGES[0].id);
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const bridge = BRIDGES.find((b) => b.id === selectedId)!;
  const cfg = SEVERITY_CONFIG[bridge.severity];

  function downloadTxt() {
    setLoading(true);
    setDone(false);
    setTimeout(() => {
      const content = generateTxtContent(bridge);
      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `BridgeGuard-Report-${bridge.id}-${Date.now()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setLoading(false);
      setDone(true);
    }, 1500);
  }

  function downloadPdf() {
    setLoading(true);
    setTimeout(() => {
      const now = new Date();
      const dateStr = now.toLocaleDateString("en-PK", {
        year: "numeric", month: "long", day: "numeric",
      });
      const timeStr = now.toLocaleTimeString("en-PK");
      const reportId = `BG-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}-${bridge.id.toUpperCase()}`;

      const h = (s: string) =>
        String(s)
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/"/g, "&quot;")
          .replace(/'/g, "&#39;");

      const recommendation = h(
        bridge.severity === "CRITICAL"
          ? "IMMEDIATE ACTION: Engineering inspection within 48 hours. Do not delay. Reduce load limits until cleared by engineer."
          : bridge.severity === "WARNING"
          ? "ACTION REQUIRED: Engineering inspection within 14 days. Monitor continuously. Document any new anomalies."
          : bridge.severity === "WATCH"
          ? "MONITOR: Continue standard monitoring. Review readings weekly. No immediate action required."
          : "NO ACTION: All systems within normal range. Next scheduled review in 30 days."
      );

      const readingsRows = Array.from({ length: 10 }, (_, i) => {
        const t = new Date(Date.now() - (10 - i) * 30000);
        const timeLabel = `${String(t.getHours()).padStart(2, "0")}:${String(t.getMinutes()).padStart(2, "0")}:${String(t.getSeconds()).padStart(2, "0")}`;
        const rms = bridge.severity === "CRITICAL"
          ? (2.2 + Math.random() * 0.9).toFixed(3)
          : bridge.severity === "WARNING"
          ? (0.6 + Math.random() * 0.4).toFixed(3)
          : (0.22 + Math.random() * 0.2).toFixed(3);
        const status = parseFloat(rms) > 0.5 ? "HIGH" : "NORMAL";
        const statusColor = status === "HIGH" ? "#b91c1c" : "#065f46";
        return `<tr>
          <td style="padding:6px 8px; border:1px solid #ccc; font-family:monospace">${timeLabel}</td>
          <td style="padding:6px 8px; border:1px solid #ccc; font-family:monospace; text-align:right">${rms}</td>
          <td style="padding:6px 8px; border:1px solid #ccc; color:${statusColor}; font-weight:bold">${status}</td>
        </tr>`;
      }).join("");

      const printWindow = window.open("", "_blank");
      if (!printWindow) return;
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>BridgeGuard Report — ${bridge.name}</title>
          <style>
            @page {
              size: A4;
              margin: 18mm 16mm 22mm 16mm;
              @bottom-center {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 10px;
                color: #666;
              }
              @bottom-left {
                content: "${reportId}";
                font-size: 9px;
                color: #999;
              }
              @bottom-right {
                content: "${dateStr}";
                font-size: 9px;
                color: #999;
              }
            }
            html { counter-reset: page; }
            body {
              font-family: 'Helvetica Neue', Arial, sans-serif;
              font-size: 11px;
              line-height: 1.5;
              color: #111;
              margin: 0;
              padding: 0;
            }
            .logo-block {
              border: 2px solid #0F6E56;
              padding: 14px 18px;
              margin-bottom: 14px;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .logo-block .brand {
              font-size: 20px;
              font-weight: 800;
              letter-spacing: 1px;
              color: #0F6E56;
            }
            .logo-block .brand small {
              display: block;
              font-size: 11px;
              font-weight: 500;
              color: #555;
              letter-spacing: 0;
              margin-top: 2px;
            }
            .logo-block .meta {
              text-align: right;
              font-size: 10px;
              color: #444;
            }
            h1 {
              text-align: center;
              font-size: 18px;
              margin: 18px 0 2px 0;
              color: #111;
            }
            h1 .urdu {
              display: block;
              font-size: 15px;
              color: #555;
              font-weight: 500;
              margin-top: 4px;
              direction: rtl;
            }
            .subtitle {
              text-align: center;
              font-size: 11px;
              color: #666;
              margin-bottom: 16px;
            }
            h2 {
              font-size: 13px;
              color: #0F6E56;
              border-bottom: 1px solid #0F6E56;
              padding-bottom: 3px;
              margin: 18px 0 8px 0;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .info-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 4px 18px;
              font-size: 11px;
            }
            .info-grid .row {
              display: flex;
              justify-content: space-between;
              padding: 3px 0;
              border-bottom: 1px dotted #ddd;
            }
            .info-grid .label { color: #555; }
            .info-grid .value { font-weight: 600; color: #111; }
            .score-block {
              display: flex;
              align-items: center;
              gap: 24px;
              border: 1px solid #ddd;
              padding: 14px;
              margin: 10px 0;
              background: #fafafa;
            }
            .score-block .big {
              font-size: 48px;
              font-weight: 800;
              color: ${cfg.bar};
              line-height: 1;
            }
            .score-block .big small {
              font-size: 14px;
              color: #666;
              font-weight: 500;
            }
            .badge {
              display: inline-block;
              padding: 4px 14px;
              border-radius: 20px;
              font-weight: 700;
              font-size: 12px;
              background: ${cfg.bgHex};
              color: ${cfg.textHex};
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .photo-placeholder {
              border: 2px dashed #aaa;
              padding: 40px 10px;
              text-align: center;
              color: #666;
              font-style: italic;
              margin: 10px 0;
              background: #fafafa;
            }
            table.readings {
              width: 100%;
              border-collapse: collapse;
              font-size: 11px;
            }
            table.readings th {
              background: #0F6E56;
              color: white;
              padding: 6px 8px;
              text-align: left;
              font-size: 11px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
            }
            .ai-box {
              border-left: 4px solid #0F6E56;
              background: #f4f8f6;
              padding: 10px 14px;
              font-size: 11.5px;
              line-height: 1.6;
            }
            .rec-box {
              border: 1px solid #e5a000;
              background: #fff8e1;
              padding: 10px 14px;
              font-size: 11.5px;
            }
            .signature-section {
              margin-top: 28px;
              page-break-inside: avoid;
            }
            .signature-section h3 {
              font-size: 12px;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              color: #0F6E56;
              margin: 0 0 8px 0;
            }
            .signature-table td {
              padding: 14px;
              border: 1px solid #ccc;
              width: 50%;
              vertical-align: top;
              font-size: 11px;
              line-height: 2;
            }
            .signature-table strong {
              display: block;
              margin-bottom: 6px;
              font-size: 11.5px;
            }
            .footer-note {
              margin-top: 18px;
              padding-top: 8px;
              border-top: 1px solid #ccc;
              font-size: 9.5px;
              color: #666;
              text-align: center;
            }
          </style>
        </head>
        <body>

          <div class="logo-block">
            <div class="brand">
              BridgeGuard AI
              <small>AI-Powered Structural Health Monitoring · Sindh, Pakistan</small>
            </div>
            <div class="meta">
              Report ID: <strong>${h(reportId)}</strong><br/>
              Generated: ${h(dateStr)}<br/>
              Time: ${h(timeStr)}
            </div>
          </div>

          <h1>
            Bridge Health Report
            <span class="urdu">برج گارڈ اے آئی — پل صحت رپورٹ</span>
          </h1>
          <div class="subtitle">
            Official Structural Assessment — Government of Sindh · Highways Department
          </div>

          <h2>1. Bridge Identification</h2>
          <div class="info-grid">
            <div class="row"><span class="label">Bridge Name:</span><span class="value">${h(bridge.name)}</span></div>
            <div class="row"><span class="label">Location:</span><span class="value">${h(bridge.location)}</span></div>
            <div class="row"><span class="label">Sensor ID:</span><span class="value">${h(bridge.sensor_id)}</span></div>
            <div class="row"><span class="label">Review Status:</span><span class="value">${h(bridge.review_status === "FINAL" ? "Final — approved" : "Pending human review")}</span></div>
          </div>

          <h2>2. Risk Assessment</h2>
          <div class="score-block">
            <div class="big">${bridge.risk_score}<small>/100</small></div>
            <div>
              <span class="badge">${h(cfg.label)}</span>
              <div style="margin-top:6px; font-size:11px; color:#555">
                Severity band derived from last 10 accelerometer readings.
              </div>
            </div>
          </div>

          <h2>3. Bridge Inspection Photo</h2>
          <div class="photo-placeholder">
            Bridge inspection photo — attach separately<br/>
            <span style="font-size:10px; color:#999">(Insert 4:3 landscape image of the inspected span here)</span>
          </div>

          <h2>4. AI Risk Explanation (Agent 3 Output)</h2>
          <div class="ai-box">${h(bridge.explanation)}</div>

          <h2>5. Recommendation</h2>
          <div class="rec-box"><strong>Engineer Action:</strong> ${recommendation}</div>

          <h2>6. Recent Sensor Readings (Last 10)</h2>
          <table class="readings">
            <thead>
              <tr>
                <th style="width:40%">Time (PKT)</th>
                <th style="width:35%">RMS (m/s²)</th>
                <th style="width:25%">Status</th>
              </tr>
            </thead>
            <tbody>
              ${readingsRows}
            </tbody>
          </table>

          <h2>7. Active Alerts</h2>
          <div style="font-size:11px">
            ${bridge.alerts.length === 0
              ? "<em>No active alerts at time of report generation.</em>"
              : bridge.alerts.map(a =>
                  `<div style="padding:4px 0; border-bottom:1px dotted #ddd">
                    <strong style="color:${SEVERITY_CONFIG[a.severity].textHex}; background:${SEVERITY_CONFIG[a.severity].bgHex}; padding:2px 8px; border-radius:10px; font-size:10px">${h(a.severity)}</strong>
                    &nbsp;${h(a.time)} — ${h(a.message)}
                  </div>`
                ).join("")
            }
          </div>

          <div class="signature-section">
            <h3>Official Sign-off</h3>
            <table class="signature-table" style="width:100%; border-collapse:collapse">
              <tr>
                <td>
                  <strong>Prepared by (Engineer):</strong>
                  Name: _______________________<br/>
                  Signature: __________________<br/>
                  Date: _______________________
                </td>
                <td>
                  <strong>Reviewed by (Authority):</strong>
                  Name: _______________________<br/>
                  Designation: ________________<br/>
                  Official Stamp: [ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ]
                </td>
              </tr>
            </table>
          </div>

          <div class="footer-note">
            This report was generated automatically by BridgeGuard AI v1.0.<br/>
            Risk scores are computed deterministically from calibrated accelerometer data.<br/>
            AI explanations are produced by Agent 3 (Risk Reasoning Agent). Critical recommendations
            require human engineer sign-off before any action is taken.<br/>
            BridgeGuard AI — Protecting Pakistan's Bridges
          </div>

        </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
      setLoading(false);
      setDone(true);
    }, 1000);
  }

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">
          Bridge Health Reports
        </h1>
        <p className="text-sm text-gray-500 mt-1">
          Generate official reports for government submission
          or engineering review. Export as TXT or PDF.
        </p>
      </div>

      <div className="bg-white border border-gray-100 rounded-xl p-6 mb-6 shadow-sm">
        <h2 className="text-sm font-semibold text-gray-700 mb-4">
          Generate a new report
        </h2>

        <div className="mb-4">
          <label className="text-xs text-gray-500 mb-2 block font-medium">
            Select bridge
          </label>
          <select
            value={selectedId}
            onChange={(e) => {
              setSelectedId(e.target.value);
              setDone(false);
            }}
            className="w-full p-3 border border-gray-200 rounded-lg text-sm text-gray-700 bg-white focus:outline-none focus:border-gray-400">
            {BRIDGES.map((b) => (
              <option key={b.id} value={b.id}>
                {b.name} — {SEVERITY_CONFIG[b.severity].label}
              </option>
            ))}
          </select>
        </div>

        <div className="p-3 rounded-lg mb-4 text-xs"
          style={{ background: cfg.bgHex, color: cfg.textHex }}>
          <strong>Current status:</strong> Risk score{" "}
          {bridge.risk_score}/100 · {cfg.label} ·{" "}
          {bridge.alerts.length} active alert{bridge.alerts.length !== 1 ? "s" : ""}
        </div>

        <div className="flex gap-3">
          <button
            onClick={downloadTxt}
            disabled={loading}
            className="flex-1 py-3 rounded-lg text-sm font-semibold border-2 transition-opacity disabled:opacity-60"
            style={{
              borderColor: "#0F6E56",
              color: "#0F6E56",
              background: "white"
            }}>
            {loading ? "Generating..." : "📄 Download TXT"}
          </button>
          <button
            onClick={downloadPdf}
            disabled={loading}
            className="flex-1 py-3 rounded-lg text-sm font-semibold text-white transition-opacity disabled:opacity-60"
            style={{ backgroundColor: "#0F6E56" }}>
            {loading ? "Generating..." : "📑 Download PDF"}
          </button>
        </div>

        {loading && (
          <p className="text-xs text-gray-400 mt-3 text-center">
            Assembling report from all 5 agent outputs...
          </p>
        )}

        {done && (
          <div className="mt-4 p-4 rounded-lg"
            style={{ background: "#eaf3de",
                     border: "0.5px solid #3B6D11" }}>
            <p className="text-sm font-semibold mb-1"
              style={{ color: "#3B6D11" }}>
              ✓ Report generated successfully
            </p>
            <p className="text-xs text-gray-500">
              For PDF: allow pop-ups and use
              &quot;Save as PDF&quot; in the print dialog.
            </p>
          </div>
        )}
      </div>

      <div className="bg-white border border-gray-100 rounded-xl p-6 shadow-sm">
        <h2 className="text-sm font-semibold text-gray-700 mb-4">
          What the report includes
        </h2>
        <div className="grid grid-cols-2 gap-3">
          {[
            "Bridge name, location, sensor ID",
            "Risk score (0-100) and severity",
            "AI explanation in plain language",
            "Last 10 sensor readings with RMS",
            "Active alerts with timestamps",
            "Maintenance recommendation",
            "5-agent pipeline attribution",
            "Report timestamp and metadata",
          ].map((item) => (
            <div key={item}
              className="flex items-center gap-2 text-sm text-gray-600">
              <span style={{ color: "#0F6E56" }}>✓</span>
              {item}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
